version: '3.3'

networks:
        teste-network:
                driver: bridge

services:
        nginx-master:
                image: nginx:1.19.1-alpine
                container_name: nginx-master
                ports:
                        - 80:80
                        - 443:443
                expose:
                    - "80"
                    - "443"
                networks:
                        - teste-network
                restart: always
                volumes:
                        - ./nginx/master.conf:/etc/nginx/conf.d/default.conf

        nginx-node0:
                image: nginx:1.19.1-alpine
                container_name: nginx-node0
                expose:
                    - "80"
                    - "443"
                networks:
                        - teste-network
                restart: always
                depends_on:
                        - nginx-master
                volumes:
                        - ./nginx/www/node0:/usr/share/nginx/html
                        
        nginx-node1:
                image: nginx:1.19.1-alpine
                container_name: nginx-node1
                expose:
                    - "80"
                    - "443"
                networks:
                        - teste-network
                restart: always
                depends_on:
                        - nginx-master
                volumes:
                        - ./nginx/www/node1:/usr/share/nginx/html/app1
                        
        nginx-node2:
                image: nginx:1.19.1-alpine
                container_name: nginx-node2
                expose:
                    - "80"
                    - "443"
                networks:
                        - teste-network
                restart: always
                depends_on:
                        - nginx-master
                volumes:
                        - ./nginx/www/node2:/usr/share/nginx/html/app2
                        

