version: '3.3'

networks:
        teste-network:
                driver: bridge

services:
        nginx-master:
                image: nginx:1.19.1-alpine
                container_name: nginx-master
                ports:
                        - 80:80
                        - 443:443
                expose:
                    - "80"
                    - "443"
                networks:
                        - teste-network
                restart: always
                volumes:
                        - ./nginx/master.conf:/etc/nginx/conf.d/defaults.conf:ro

        nginx-node1:
                image: nginx:1.19.1-alpine
                container_name: nginx-node1
                expose:
                    - "80"
                    - "443"
                networks:
                        - teste-network
                restart: always
                depends_on:
                        - nginx-master
                volumes:
                        - ./nginx/node1.conf:/etc/nginx/conf.d/defaults.conf:ro

